### ISSUE TITLE
Make the default padding adjustable

### ISSUE THREAD

**Issue by insacc** [GuilhE/android-circular-progress-view#15]
The view adds a default padding around the view which is non-configurable. It'd be much much better if this's also configurable.

**Comment by GuilhE** [comment]
Hello insacc, thank you for your input.
I'll look into it, in the meanwhile, you're welcome to collaborate in this project and develop such feature.

Thanks!

**Comment by GuilhE** [comment]
OK, so after a quick look:
`private final float mDefaultViewPadding = dpToPx(DEFAULT_VIEW_PADDING_DP);`
It's final because it's not suppose to be changed, and here's why:

![Screenshot 2019-08-19 at 23 32 03](https://user-images.githubusercontent.com/2677139/63304055-9d0bd180-c2d9-11e9-9aee-20dc9b11a81f.png)
![Screenshot 2019-08-19 at 23 32 14](https://user-images.githubusercontent.com/2677139/63304056-9da46800-c2d9-11e9-8284-8e0f6bc33aa1.png)

That padding exists to make sure none of the drawn elements (progress, shadow, thumb) is drawn outside the "draw area". Why would you want to change the padding of the view? You can change it's size by the method `public void setSize(int size)`. If you need some sort of padding, change it in the parent view.
